@startuml
state "= Play: Test 1" as play_1 {
    play_1 : | hosts | all |
    state "== debug" as task_1
    task_1 : Action **debug**
    task_1 : | msg | Test 1 |
}
[*] --> task_1
task_1 --> [*]
@enduml
